export const MEDIA_LIMITS = {
  MAX_IMAGES: 10,
  MAX_VIDEOS: 3,
  MAX_VOICE_RECORDINGS: 5,
  MAX_IMAGE_SIZE_MB: 10,
  MAX_IMAGE_RAW_SIZE_MB: 50,
  MAX_VIDEO_SIZE_MB: 100,
  MAX_VIDEO_DURATION_SEC: 300,
  MAX_IMAGE_RESOLUTION: 2048,
  MAX_VOICE_DURATION_SEC: 1800,
}
