export const equipmentOptions = {
  en: [
    { value: "barbell", label: "Barbell" },
    { value: "dumbbell", label: "Dumbbell" },
    { value: "machine", label: "Machine" },
    { value: "smith", label: "Smith" },
    { value: "cable", label: "Cable" },
    { value: "rope", label: "Rope" },
    { value: "bodyweight", label: "Bodyweight" },
    { value: "gripper", label: "Gripper" },
    { value: "band", label: "Band" },
    { value: "ball", label: "Ball" },
    { value: "wheel", label: "Wheel" },
  ],
  fi: [
    { value: "barbell", label: "Tanko" },
    { value: "dumbbell", label: "Käsipaino" },
    { value: "machine", label: "Laite" },
    { value: "smith", label: "Smith-laite" },
    { value: "cable", label: "Kaapeli" },
    { value: "rope", label: "Köysi" },
    { value: "bodyweight", label: "Oma paino" },
    { value: "gripper", label: "Puristin" },
    { value: "band", label: "Kuminauha" },
    { value: "ball", label: "Pallo" },
    { value: "wheel", label: "Pyörä" },
  ],
};

export const muscleGroupOptions = {
  en: [
    { value: "chest", label: "Chest" },
    { value: "quads", label: "Quads" },
    { value: "hamstrings", label: "Hamstrings" },
    { value: "biceps", label: "Biceps" },
    { value: "triceps", label: "Triceps" },
    { value: "lats", label: "Lats" },
    { value: "abs", label: "Abs" },
    { value: "calves", label: "Calves" },
    { value: "upper_back", label: "Upper back" },
    { value: "forearms", label: "Forearms" },
    { value: "full_body", label: "Full body" },
    { value: "side_delts", label: "Side delts" },
    { value: "legs", label: "Legs" },
    { value: "obliques", label: "Obliques" },
    { value: "front_delts", label: "Front delts" },
    { value: "traps", label: "Traps" },
  ],
  fi: [
    { value: "chest", label: "Rinta" },
    { value: "quads", label: "Etureidet" },
    { value: "hamstrings", label: "Takareidet" },
    { value: "biceps", label: "Hauis" },
    { value: "triceps", label: "Ojentaja" },
    { value: "lats", label: "Leveä selkälihas" },
    { value: "abs", label: "Vatsat" },
    { value: "calves", label: "Pohkeet" },
    { value: "upper_back", label: "Yläselkä" },
    { value: "forearms", label: "Kyynärvarret" },
    { value: "full_body", label: "Koko keho" },
    { value: "side_delts", label: "Sivut hartiat" },
    { value: "legs", label: "Jalat" },
    { value: "obliques", label: "Vino vatsalihas" },
    { value: "front_delts", label: "Etuhartiat" },
    { value: "traps", label: "Epäkkäät" },
  ],
};

export const mainGroupOptions = {
  en: [
    { value: "chest", label: "Chest" },
    { value: "legs", label: "Legs" },
    { value: "arms", label: "Arms" },
    { value: "shoulders", label: "Shoulders" },
    { value: "back", label: "Back" },
    { value: "core", label: "Core" },
    { value: "cardio", label: "Cardio" },
  ],
  fi: [
    { value: "chest", label: "Rinta" },
    { value: "legs", label: "Jalat" },
    { value: "arms", label: "Kädet" },
    { value: "shoulders", label: "Hartiat" },
    { value: "back", label: "Selkä" },
    { value: "core", label: "Keskivartalo" },
    { value: "cardio", label: "Kestävyys" },
  ],
};